#!/usr/bin/bash

VPN=`networksetup -showpppoestatus "VPN"`
if [[ $VPN =~ "disconnected" ]]
    then
osascript -e 'tell application "System Events"' -e 'tell current location of network preferences' -e 'set VPNservice to service "VPN"' -e 'if exists VPNservice then connect VPNservice' -e 'end tell' -e 'end tell' &> /dev/null
echo "Connecting to VPN"
    else
osascript -e 'tell application "System Events"' -e 'tell current location of network preferences' -e 'set VPNservice to service "VPN"' -e 'if exists VPNservice then disconnect VPNservice' -e 'end tell' -e 'end tell' &> /dev/null
    echo "Disconnecting VPN"
fi
