#!/bin/zsh
# A FZF clipboard menu for BetterTouchTool

SQLPATH=$(find ~/Library/Application\ Support/BetterTouchTool/ -maxdepth 1 -name "BTTClipboardManager_*.sqlite")
sqlite-utils "$SQLPATH" "select Z_PK, ZPREVIEWTEXT from ZBTTCLIP" \
| jq -r --raw-output0 '.[].ZPREVIEWTEXT' \
| fzf +m --read0 --tac --listen 6265 \
  --no-info --no-wrap --multi --no-multi-line \
  --prompt='' \
  --ghost '' \
  --bind change:first \
  --bind 'alt-r:reload(sqlite-utils "$HOME/Library/Application Support/BetterTouchTool/BTTClipboardManager_20241210.sqlite" "select Z_PK, ZPREVIEWTEXT from ZBTTCLIP" | jq -r --raw-output0 ".[].ZPREVIEWTEXT")+clear-query+clear-selection' \
  --bind 'enter:execute-silent(cat {+f} | pbcopy;yabai -m window --focus recent || yabai -m window --focus last)+clear-query+clear-selection' \
  --bind 'alt-e:execute-silent(cat {+f} | micro)+clear-query+clear-selection' \
  --bind 'alt-c:execute-silent(cat {+f} | pbcopy)+clear-query+clear-selection' \
  --bind 'esc:clear-query+clear-selection' \
  --bind 'alt-q:abort' \
  --color 'input:#fd971f,preview-border:#fd971f' \
  --preview-window='top:nohidden:wrap:50%:noinfo' \
  --preview='echo {} | \
             highlight \
                 --out-format=truecolor \
                 --syntax=zsh | \
             rg -i \
                 --field-match-separator=" " \
                 --field-context-separator=" " \
                 --no-context-separator \
                 --no-line-number \
                 --color=always \
                 --colors=line:style:bold \
                 --colors "match:bg:yellow" \
                 --colors "match:fg:black" \
                 --context 50 {q}' &> /dev/null
