#!/bin/bash

if [[ "$(uname -s)" != 'Darwin' ]]; then
  echo 'Sorry, this script only works on macOS'
  exit 1
fi

exec ls -d /Volumes/* | fzf --layout=reverse-list --bind 'alt-c:execute-silent(echo {} | pbcopy)+abort' -e -i | sed "s/^/'/;s/$/'/" | xargs hdiutil detach
