#!/bin/bash

if [[ "$(uname -s)" != 'Darwin' ]]; then
  echo 'Sorry, this script only works on macOS'
  exit 1
fi

exec osascript -e 'tell application "Finder" to eject (every disk whose ejectable is true)'
