#!/bin/zsh

if [[ "$(uname -s)" != 'Darwin' ]]; then
  echo 'This script only works on macOS'
  exit 1
fi

df -h | cut -d '%' -f3 | tail -n +14 | sed 's/^ *//' | \
     fzf --layout=reverse-list \
     --bind 'alt-c:execute-silent(echo {} | pbcopy)+abort' \
     -e -i | \
     sed "s/^/'/;s/$/'/" | \
     xargs hdiutil eject
     # xargs hdiutil detach
