#!/bin/bash
# Clipboard manager CopyQ through fzf

read -r -d '' copyqjs << EOM
for (var i = 0; i < size(); i++) {
  var lines = str(read(i)).split(/[\r\n]+/);
  var line = "";
  line = lines;
  if (line == "") {
      line = '  image file';
  }
  print(i + " " + line + "\n");
}
EOM

pick="$(echo "$copyqjs" | \
        /Applications/CopyQ.app/Contents/MacOS/CopyQ eval - | \
        fzf --preview-window nohidden --no-info --multi \
            --bind 'alt-e:execute(/Applications/CopyQ.app/Contents/MacOS/CopyQ read {1} | xargs -0 echo | micro)' \
            --bind 'alt-backspace:execute(/Applications/CopyQ.app/Contents/MacOS/CopyQ remove {1})' \
            --preview='/Applications/CopyQ.app/Contents/MacOS/CopyQ read {1} | \
        highlight --out-format=truecolor \
            --syntax=zsh \
            --style=bellavene | \
        rga  -i \
            --field-match-separator=" " \
            --field-context-separator=" " \
            --no-context-separator \
            --no-line-number \
            --color=always \
            --colors=line:style:bold \
            --colors 'match:bg:magenta' \
            --colors 'match:fg:black' \
            --context 50 {q}' | \
        awk '{print $1}'
)"


if [[ "$pick" != "" ]]; then
    /Applications/CopyQ.app/Contents/MacOS/CopyQ select "$pick"
fi


# rg -i --pretty --context 2 {q}
# --preview='highlight -O ansi --style=base16/bellavene -l {} 2> /dev/null
