#!/usr/bin/python3

import sys
from ResolveLib.python_get_resolve import GetResolve
import ResolveLib.ianresolvelib as r
import DaVinciResolveScript as dvr_script
# import re
# import subprocess

if len(sys.argv) < 1:
	print("No defined path")
	sys.exit()

resolve = dvr_script.scriptapp("Resolve")
projectManager = resolve.GetProjectManager()
project = projectManager.GetCurrentProject()
mediapool = project.GetMediaPool()
timelineName = "Source"
root = mediapool.GetRootFolder()
newfolder = "Source New"
folder = mediapool.AddSubFolder(root, newfolder)
# timeline = mediapool.CreateEmptyTimeline(timelineName)
# timeline = project.GetCurrentTimeline()
mediaPath = sys.argv[1]

clips = resolve.GetMediaStorage().AddItemListToMediaPool(mediaPath)
# for clip in clips:
mediapool.CreateTimelineFromClips(timelineName, clips)
